[build]
  functions = "./functions/dist"
  #fetch files from dropbox before build
  command = "node_modules/.bin/tsc -p ./.bin/tsconfig.json && node .bin/dist/index.js && hexo generate && netlify-lambda build ./functions"
  #command = "hexo generate && netlify-lambda build ./functions"
[context.production]
  environment = { NODE_VERSION = "8" }
[[redirects]]
  from = "/:slug/images/:img"
  to = "/images/:img"
  force = true
