[build]
  functions = "./functions/dist"
  command = "hexo generate && netlify-lambda build ./functions"
[context.production]
  environment = { DROPBOX_APP_KEY = "APP_KEY", DROPBOX_APP_SECRET = "APP_SECRET", NODE_ENV = "10" }