import * as fs from 'fs';


const func = function () {
    console.log(`build begin: ${process.cwd()}`);

    fs.writeFileSync('./source/_posts/test.md', "#This is generated by build script.");

    console.log('build end');
};

func();